# Generated by Django 2.2.16 on 2022-06-20 11:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220406_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(10, 'Максимальная оценка - 10!'), django.core.validators.MinValueValidator(1, 'Минимальная оценка - 1!')], verbose_name='Оценка'),
        ),
    ]
